/**
 * Automatically generated by palmares on 2024-07-24T16:24:51.813Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '002_default_auto_migration_1721838291813',
  database: 'default',
  dependsOn: 'create_palmares_migration_table',
  operations: [
    new actions.CreateModel(
      "Company",
      {
        id: models.fields.AutoField.new({
          databaseName: "id",
          underscored: false,
          customAttributes: {}
        }),
        name: models.fields.CharField.new({
          allowBlank: true,
          maxLength: 255,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "name",
          underscored: false,
          customAttributes: {}
        }),
        address: models.fields.CharField.new({
          allowBlank: true,
          maxLength: 255,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: true,
          unique: false,
          dbIndex: false,
          databaseName: "address",
          underscored: false,
          customAttributes: {}
        }),
        translatable: models.fields.TranslatableField.new({
          translate: async () => {
            const { DataTypes } = require('sequelize');
            return { type: DataTypes.STRING }
          }
        })
      ,
      },
      {
        abstract: false,
        underscored: true,
        tableName: "companies",
        managed: true,
        ordering: [],
        indexes: [],
        databases: [],
        customOptions: {}
      }
    ),
    new actions.CreateModel(
      "User",
      {
        id: models.fields.AutoField.new({
          databaseName: "id",
          underscored: false,
          customAttributes: {}
        }),
        uuid: models.fields.UuidField.new({
          allowBlank: true,
          autoGenerate: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: true,
          dbIndex: false,
          databaseName: "uuid",
          underscored: false,
          customAttributes: {}
        }),
        name: models.fields.CharField.new({
          allowBlank: true,
          maxLength: 255,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: true,
          unique: false,
          dbIndex: true,
          databaseName: "name",
          underscored: false,
          customAttributes: {}
        }),
        age: models.fields.IntegerField.new({
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: true,
          databaseName: "age",
          underscored: false,
          customAttributes: {}
        }),
        userType: models.fields.EnumField.new({
          choices: ['admin', 'user'],
          primaryKey: false,
          defaultValue: "admin",
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "user_type",
          underscored: false,
          customAttributes: {}
        }),
        price: models.fields.DecimalField.new({
          maxDigits: 5,
          decimalPlaces: 2,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: true,
          unique: false,
          dbIndex: false,
          databaseName: "price",
          underscored: false,
          customAttributes: {}
        }),
        isActive: models.fields.BooleanField.new({
          primaryKey: false,
          defaultValue: true,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "is_active",
          underscored: false,
          customAttributes: {}
        }),
        companyId: models.fields.ForeignKeyField.new({
          relatedTo: "Company",
          toField: "id",
          onDelete: models.fields.ON_DELETE.CASCADE,
          customName: undefined,
          relationName: "company",
          relatedName: "usersOfCompany",
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "company_id",
          underscored: false,
          customAttributes: {}
        }),
        updatedAt: models.fields.DateField.new({
          autoNow: true,
          autoNowAdd: false,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "updated_at",
          underscored: false,
          customAttributes: {}
        }),
        createdAt: models.fields.DateField.new({
          autoNow: false,
          autoNowAdd: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "created_at",
          underscored: false,
          customAttributes: {}
        }),
      },
      {
        abstract: false,
        underscored: true,
        tableName: "users",
        managed: true,
        ordering: [],
        indexes: [],
        databases: ["default"],
        customOptions: {}
      }
    )
  ]
};
