/**
 * Automatically generated by palmares on 2022-07-28T03:42:49.353Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '003_default_auto_migration_1658979769353',
  database: 'default',
  dependsOn: '002_default_auto_migration_1658865359917',
  operations: [
    new actions.ChangeField(
      'User',
      'firstName',
      new models.fields.CharField({
        allowBlank: true,
        maxLength: 255,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: 'first_name',
        underscored: true,
        customAttributes: {},
      }),
      new models.fields.CharField({
        allowBlank: true,
        maxLength: 255,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: true,
        databaseName: 'first_name',
        underscored: true,
        customAttributes: {},
      })
    ),
    new actions.ChangeField(
      'User',
      'lastName',
      new models.fields.CharField({
        allowBlank: true,
        maxLength: 255,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: true,
        databaseName: 'last_name',
        underscored: true,
        customAttributes: {},
      }),
      new models.fields.CharField({
        allowBlank: true,
        maxLength: 255,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: 'last_name',
        underscored: true,
        customAttributes: {},
      })
    ),
    new actions.ChangeField(
      'User',
      'dependsOn',
      new models.fields.ForeignKeyField({
        relatedTo: 'User',
        toField: 'uuid',
        onDelete: models.fields.ON_DELETE.CASCADE,
        customName: undefined,
        relatedName: 'userUsers',
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: 'depends_on',
        underscored: true,
        customAttributes: {},
      }),
      new models.fields.ForeignKeyField({
        relatedTo: 'User',
        toField: 'uuid',
        onDelete: models.fields.ON_DELETE.CASCADE,
        customName: undefined,
        relatedName: 'userUsers',
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: 'depends_on',
        underscored: true,
        customAttributes: {},
      })
    ),
  ],
};
