/**
 * Automatically generated by palmares on 2023-01-24T18:04:13.148Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '003_default_auto_migration_1674583453148',
  database: 'default',
  dependsOn: '002_default_auto_migration_1671759713784',
  operations: [
    new actions.ChangeField(
      'Photo',
      'name',
      models.fields.CharField.new({
        allowBlank: true,
        maxLength: 255,
        primaryKey: false,
        defaultValue: null,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: 'name',
        underscored: false,
        customAttributes: {},
      }),
      models.fields.CharField.new({
        allowBlank: true,
        maxLength: 255,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: 'name',
        underscored: false,
        customAttributes: {},
      })
    ),
    new actions.ChangeField(
      'Photo',
      'userId',
      models.fields.ForeignKeyField.new({
        relatedTo: 'User',
        toField: 'id',
        onDelete: models.fields.ON_DELETE.CASCADE,
        customName: undefined,
        relationName: 'user',
        relatedName: 'userPhotos',
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: true,
        dbIndex: false,
        databaseName: 'user_id',
        underscored: false,
        customAttributes: {},
      }),
      models.fields.ForeignKeyField.new({
        relatedTo: 'User',
        toField: 'id',
        onDelete: models.fields.ON_DELETE.CASCADE,
        customName: undefined,
        relationName: 'user',
        relatedName: 'userPhotos',
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: 'user_id',
        underscored: false,
        customAttributes: {},
      })
    ),
    new actions.ChangeField(
      'Post',
      'number',
      models.fields.IntegerField.new({
        primaryKey: false,
        defaultValue: 2,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: 'number',
        underscored: false,
        customAttributes: {},
      }),
      models.fields.IntegerField.new({
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: 'number',
        underscored: false,
        customAttributes: {},
      })
    ),
  ],
};
