/**
 * Automatically generated by palmares on 2023-01-31T14:57:05.487Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '004_default_auto_migration_1675177025487',
  database: 'default',
  dependsOn: '003_default_auto_migration_1674943386239',
  operations: [
    new actions.ChangeField(
      'Photo',
      'userId',
      models.fields.ForeignKeyField.new({
        relatedTo: 'User',
        toField: 'id',
        onDelete: models.fields.ON_DELETE.CASCADE,
        customName: undefined,
        relationName: 'user',
        relatedName: 'userPhotos',
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: 'user_id',
        underscored: false,
        customAttributes: {},
      }),
      models.fields.ForeignKeyField.new({
        relatedTo: 'User',
        toField: 'id',
        onDelete: models.fields.ON_DELETE.CASCADE,
        customName: undefined,
        relationName: 'user',
        relatedName: 'userPhotos',
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: true,
        dbIndex: false,
        databaseName: 'user_id',
        underscored: false,
        customAttributes: {},
      })
    ),
  ],
};
