export const FRAMEWORK_NAME: string = 'palmares';
export const ERR_MODULE_NOT_FOUND: string = 'MODULE_NOT_FOUND';


// logging
export const LOGGING_USING_SETTINGS_FROM_PATH: string = 'USING_SETTINGS_FROM_PATH';
export const LOGGING_SETTINGS_MODULE_NOT_FOUND: string = 'SETTINGS_MODULE_NOT_FOUND';
export const LOGGING_DATABASE_MODELS_NOT_FOUND: string = 'DATABASE_MODELS_NOT_FOUND';
export const LOGGING_DATABASE_IS_NOT_CONNECTED: string = 'DATABASE_IS_NOT_CONNECTED';
export const LOGGING_DATABASE_CLOSING: string = 'DATABASE_CLOSING';
export const LOGGING_ADAPTER_NOT_FOUND: string = 'ADAPTER_NOT_FOUND';
export const LOGGING_APP_START_SERVER: string = 'APP_START_SERVER';
export const LOGGING_APP_STOP_SERVER: string = 'APP_STOP_SERVER';