// @ts-nocheck
/** Automatically generated by @palmares/drizzle-engine on 2025-02-23T04:38:14.850Z */

import * as pdb from '@palmares/databases';
import * as drzl from 'drizzle-orm';
import * as d from 'drizzle-orm/sqlite-core';

export const Company = d.sqliteTable(
  'companies',
  {
    id: d.integer('id', { mode: 'number' }).primaryKey({ autoIncrement: true }).unique(),
    name: d.text('name', { length: 255 }).notNull(),
    isActive: d.integer('is_active', { mode: 'boolean' }).default(1).notNull()
  },
  (table) => ({
    idIdx: d.uniqueIndex('companies_id_idx').on(table.id)
  })
);
