export const FRAMEWORK_NAME = 'palmares';
export const PACKAGE_NAME = '@palmares/core';
export const ERR_MODULE_NOT_FOUND = 'MODULE_NOT_FOUND';
export const PALMARES_SETTINGS_MODULE_ENVIRONMENT_VARIABLE =
  'PALMARES_SETTINGS_MODULE';

// logging
export const LOGGING_USING_SETTINGS_FROM_PATH = 'USING_SETTINGS_FROM_PATH';
export const LOGGING_USING_SETTINGS_FROM_IMPORT = 'USING_SETTINGS_FROM_IMPORT';
export const LOGGING_SETTINGS_MODULE_NOT_FOUND = 'SETTINGS_MODULE_NOT_FOUND';
export const LOGGING_ADAPTER_NOT_FOUND = 'ADAPTER_NOT_FOUND';
export const LOGGING_APP_STOP_SERVER = 'APP_STOP_SERVER';
