/**
 * Automatically generated by palmares on 2023-10-05T14:36:07.639Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '002_default_auto_migration_1696516567639',
  database: 'default',
  dependsOn: 'create_palmares_migration_table',
  operations: [
    new actions.CreateModel(
      'Profile',
      {
        id: models.fields.AutoField.new({
          databaseName: 'id',
          underscored: false,
          customAttributes: {},
        }),
        firstName: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'first_name',
          underscored: false,
          customAttributes: {},
        }),
        lastName: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'last_name',
          underscored: false,
          customAttributes: {},
        }),
        profession: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'profession',
          underscored: false,
          customAttributes: {},
        }),
        balance: models.fields.DecimalField.new({
          maxDigits: 12,
          decimalPlaces: 2,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: true,
          unique: false,
          dbIndex: false,
          databaseName: 'balance',
          underscored: false,
          customAttributes: {},
        }),
        type: models.fields.EnumField.new({
          choices: ['client', 'contractor'],
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'type',
          underscored: false,
          customAttributes: {},
        }),
      },
      {
        abstract: false,
        underscored: true,
        tableName: 'profile',
        managed: true,
        ordering: [],
        indexes: [],
        databases: ['default'],
        customOptions: {},
      }
    ),
  ],
};
