/**
 * Automatically generated by palmares on 2024-06-28T01:28:03.614Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '006_default_auto_migration_1719538083614',
  database: 'default',
  dependsOn: '005_default_auto_migration_1719538083612',
  operations: [
    new actions.ChangeField(
      "Profile",
      "firstName",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "first_name",
        underscored: false,
        customAttributes: {}
      }),
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "first_name",
        underscored: false,
        customAttributes: {}
      })
    ),
  ]
};
