/**
 * Automatically generated by palmares on 2024-06-25T17:11:16.963Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '008_default_auto_migration_1719335476963',
  database: 'default',
  dependsOn: '007_default_auto_migration_1719335476960',
  operations: [
    new actions.ChangeField(
      "Profile",
      "firstName",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "first_name",
        underscored: false,
        customAttributes: {}
      }),
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "first_name",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
