/**
 * Automatically generated by palmares on 2023-10-05T06:33:11.645Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '002_default_auto_migration_1696487591645',
  database: 'default',
  dependsOn: 'create_palmares_migration_table',
  operations: [
    new actions.CreateModel(
      "User",
      {
        id: models.fields.AutoField.new({
          primaryKey: true,
          defaultValue: undefined,
          allowNull: false,
          unique: true,
          dbIndex: true,
          databaseName: "id",
          underscored: false,
          customAttributes: {}
        }),
        firstName: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: "",
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "first_name",
          underscored: false,
          customAttributes: {}
        }),
        lastName: models.fields.CharField.new({
          allowBlank: true,
          maxLength: 255,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: true,
          unique: false,
          dbIndex: false,
          databaseName: "last_name",
          underscored: false,
          customAttributes: {}
        }),
      },
      {
        abstract: false,
        underscored: true,
        tableName: "user",
        managed: true,
        ordering: [],
        indexes: [],
        databases: ["default"],
        customOptions: {}
      }
    )
  ]
};
