/**
* Automatically Generated by Palmares at 2021-12-24T22:07:33.368Z
* */
import { models, actions } from '@palmares/databases';

'use strict'

export default {
  name: '001_creating_models',
  databases: ['default'],
  dependsOn: "",
  operations: [
    new actions.CreateModel(
      "User",
      {
        id: new models.fields.AutoField(),
        firstName: new models.fields.CharField({ maxLength: 255 }),
        uuid: new models.fields.UUIDField({ autoGenerate: true, maxLength: 36 })
      },
      {
        tableName: 'user'
      }
    ),
    new actions.CreateModel(
      "Post",
      {
        id: new models.fields.AutoField(),
        number: new models.fields.IntegerField({
          allowNull: true,
          defaultValue: 1
        }),
        userUuid: new models.fields.ForeignKeyField({
          relatedTo: 'User',
          onDelete: models.fields.ON_DELETE.CASCADE,
          toField: 'id'
        })
      },
      {
        tableName: 'post',
        ordering: ['id']
      }
    )
  ]
};
