/**
* Automatically Generated by Palmares at 2021-12-24T22:07:33.368Z
* */
import { models, actions } from '@palmares/databases';

'use strict'

export default {
  name: '001_creating_models',
  engines: ['@palmares/sequelize-engine'],
  dependsOn: "",
  operations: [
    new actions.CreateModel(
      "LocationType",
      {
        id:new models.fields.BigAutoField({"underscored":true,"primaryKey":true,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"id","customAttributes":{}}),
        name:new models.fields.CharField({"underscored":true,"primaryKey":false,"allowBlank":false,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"name","customAttributes":{},"maxLength":200}),
        order:new models.fields.IntegerField({"underscored":true,"primaryKey":false,"defaultValue":1,"allowNull":false,"unique":false,"dbIndex":false,"databaseName":"order","customAttributes":{}}),
      },
      {
        abstract: false,
        underscored: true,
        tableName: "location_type",
        managed: true,
        ordering: ["order"],
        indexes: [],
        customOptions: {},
      }
    )
  ]
};
