/**
 * Automatically generated by palmares on 2022-07-24T04:44:04.179Z
 */

import { models, actions } from "@palmares/databases"; 

export default {
  name: '002_default_auto_migration_1658637844179',
  database: "default",
  dependsOn: "001_default_auto_migration_1658637844178",
  operations: [

  ]
};
