/**
 * Automatically generated by palmares on 2023-10-05T14:36:07.643Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '004_default_auto_migration_1696516567643',
  database: 'default',
  dependsOn: '003_default_auto_migration_1696516567641',
  operations: [
    new actions.CreateModel(
      'Jobs',
      {
        id: models.fields.AutoField.new({
          primaryKey: true,
          defaultValue: undefined,
          allowNull: false,
          unique: true,
          dbIndex: true,
          databaseName: 'id',
          underscored: false,
          customAttributes: {},
        }),
        description: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'description',
          underscored: false,
          customAttributes: {},
        }),
        price: models.fields.DecimalField.new({
          maxDigits: 12,
          decimalPlaces: 2,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'price',
          underscored: false,
          customAttributes: {},
        }),
        paid: models.fields.BooleanField.new({
          primaryKey: false,
          defaultValue: false,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'paid',
          underscored: false,
          customAttributes: {},
        }),
        paymentDate: models.fields.DateField.new({
          autoNow: true,
          autoNowAdd: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'payment_date',
          underscored: false,
          customAttributes: {},
        }),
        contractId: models.fields.ForeignKeyField.new({
          relatedTo: 'Contract',
          toField: 'id',
          onDelete: models.fields.ON_DELETE.CASCADE,
          customName: undefined,
          relationName: 'contract',
          relatedName: 'jobContracts',
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'contract_id',
          underscored: false,
          customAttributes: {},
        }),
      },
      {
        abstract: false,
        underscored: true,
        tableName: 'jobs',
        managed: true,
        ordering: [],
        indexes: [],
        databases: ['default'],
        customOptions: {},
      }
    ),
  ],
};
