export const LOGGING_DATABASE_IS_NOT_CONNECTED = 'DATABASE_IS_NOT_CONNECTED'
export const LOGGING_DATABASE_CLOSING = 'DATABASE_CLOSING'
export const LOGGING_DATABASE_MODELS_NOT_FOUND = 'DATABASE_MODELS_NOT_FOUND'
