export const LOGGING_DATABASE_IS_NOT_CONNECTED = 'DATABASE_IS_NOT_CONNECTED';
export const LOGGING_DATABASE_CLOSING = 'DATABASE_CLOSING';
export const LOGGING_DATABASE_MODELS_NOT_FOUND = 'DATABASE_MODELS_NOT_FOUND';
export const LOGGING_MIGRATIONS_NOT_FOUND = 'MIGRATIONS_NOT_FOUND';
export const LOGGING_NO_CHANGES_MADE_FOR_MIGRATIONS = 'NO_CHANGES_MADE_FOR_MIGRATIONS';
export const PACKAGE_NAME = '@palmares/databases';
