/**
 * Automatically generated by palmares on 2023-02-15T15:11:10.087Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '006_default_auto_migration_1676473870087',
  database: 'default',
  dependsOn: '005_default_auto_migration_1675177485117',
  operations: [
    new actions.CreateField(
      'User',
      'pokemonId',
      models.fields.IntegerField.new({
        primaryKey: false,
        defaultValue: 25,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: 'pokemon_id',
        underscored: false,
        customAttributes: {},
      })
    ),
  ],
};
