/**
 * Automatically generated by palmares on 2023-10-05T14:36:07.641Z
 */

import { models, actions } from '@palmares/databases';

export default {
  name: '003_default_auto_migration_1696516567641',
  database: 'default',
  dependsOn: '002_default_auto_migration_1696516567639',
  operations: [
    new actions.CreateModel(
      'Contract',
      {
        id: models.fields.AutoField.new({
          primaryKey: true,
          defaultValue: undefined,
          allowNull: false,
          unique: true,
          dbIndex: true,
          databaseName: 'id',
          underscored: false,
          customAttributes: {},
        }),
        terms: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'terms',
          underscored: false,
          customAttributes: {},
        }),
        status: models.fields.EnumField.new({
          choices: ['new', 'in_progress', 'terminated'],
          primaryKey: false,
          defaultValue: undefined,
          allowNull: true,
          unique: false,
          dbIndex: false,
          databaseName: 'status',
          underscored: false,
          customAttributes: {},
        }),
        contractorId: models.fields.ForeignKeyField.new({
          relatedTo: 'Profile',
          toField: 'id',
          onDelete: models.fields.ON_DELETE.CASCADE,
          customName: undefined,
          relationName: 'contractor',
          relatedName: 'contractorContracts',
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'contractor_id',
          underscored: false,
          customAttributes: {},
        }),
        clientId: models.fields.ForeignKeyField.new({
          relatedTo: 'Profile',
          toField: 'id',
          onDelete: models.fields.ON_DELETE.CASCADE,
          customName: undefined,
          relationName: 'client',
          relatedName: 'clientContracts',
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: 'client_id',
          underscored: false,
          customAttributes: {},
        }),
      },
      {
        abstract: false,
        underscored: true,
        tableName: 'contract',
        managed: true,
        ordering: [],
        indexes: [],
        databases: ['default'],
        customOptions: {},
      }
    ),
  ],
};
