/**
 * Automatically generated by palmares on 2024-06-25T17:10:37.364Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '005_default_auto_migration_1719335437364',
  database: 'default',
  dependsOn: '004_default_auto_migration_1696516567643',
  operations: [
    new actions.ChangeField(
      "Contract",
      "terms",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "terms",
        underscored: false,
        customAttributes: {}
      }),
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "No terms",
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "terms",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
