/**
 * Automatically generated by palmares on 2024-06-28T01:28:03.612Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '005_default_auto_migration_1719538083612',
  database: 'default',
  dependsOn: '004_default_auto_migration_1696516567643',
  operations: [
    new actions.CreateField(
      "Contract",
      "terms1",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "sei la",
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "terms1",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
