/**
 * Automatically generated by palmares on 2024-06-20T04:05:20.618Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '005_default_auto_migration_1718856320618',
  database: 'default',
  dependsOn: '004_default_auto_migration_1696516567643',
  operations: [
    new actions.CreateField(
      "Contract",
      "newColumn",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "default",
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "new_column",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
