/**
 * Automatically generated by palmares on 2024-06-21T14:35:46.073Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '006_default_auto_migration_1718980546073',
  database: 'default',
  dependsOn: '005_default_auto_migration_1718856320618',
  operations: [
    new actions.ChangeField(
      "Contract",
      "terms",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "terms",
        underscored: false,
        customAttributes: {}
      }),
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "default",
        allowNull: false,
        unique: false,
        dbIndex: false,
        databaseName: "terms",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
