/**
 * Automatically generated by palmares on 2024-06-25T17:10:58.487Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '006_default_auto_migration_1719335458487',
  database: 'default',
  dependsOn: '005_default_auto_migration_1719335437364',
  operations: [
    new actions.ChangeField(
      "Contract",
      "terms1",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "No terms",
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "terms",
        underscored: false,
        customAttributes: {}
      }),
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "No terms",
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "terms1",
        underscored: false,
        customAttributes: {}
      })
    ),
    new actions.RenameField(
      "Contract",
      "terms",
      "terms1",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: "No terms",
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "terms1",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
