/**
 * Automatically generated by palmares on 2024-06-25T17:11:16.960Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '007_default_auto_migration_1719335476960',
  database: 'default',
  dependsOn: '006_default_auto_migration_1719335458487',
  operations: [
    new actions.CreateField(
      "Contract",
      "newColumn",
      models.fields.TextField.new({
        allowBlank: true,
        primaryKey: false,
        defaultValue: undefined,
        allowNull: true,
        unique: false,
        dbIndex: false,
        databaseName: "new_column",
        underscored: false,
        customAttributes: {}
      })
    )
  ]
};
