/**
 * Automatically generated by palmares on 2024-06-25T17:11:38.777Z
 */

import { models, actions } from '@palmares/databases';


export default {
  name: '009_default_auto_migration_1719335498777',
  database: 'default',
  dependsOn: '007_default_auto_migration_1719335476960',
  operations: [
    new actions.CreateModel(
      "NewModel",
      {
        id: models.fields.AutoField.new({
          databaseName: "id",
          underscored: false,
          customAttributes: {}
        }),
        name: models.fields.TextField.new({
          allowBlank: true,
          primaryKey: false,
          defaultValue: undefined,
          allowNull: false,
          unique: false,
          dbIndex: false,
          databaseName: "name",
          underscored: false,
          customAttributes: {}
        }),
      },
      {
        abstract: false,
        underscored: true,
        tableName: "new_model",
        managed: true,
        ordering: [],
        indexes: [],
        databases: ["default"],
        customOptions: {}
      }
    )
  ]
};
